#!/bin/bash

# script to compile the code with make
# use different compiler and flags based on input argument
# search the line beginning with "F90FLAS" and replace it
# .* is the regular expression for greedy search
# Note: you need to make clean before switching compilers and/or flags

if [ $# == 0 ]
then
   echo "no input argument"
   exit 1
fi

if [ $1 == 1 ]
then
   module load intel mpich
   echo "use intel to compile with flag -O0 -g"
   echo "***************************************************"
   sed "s/^F90FLAGS = .*/F90FLAGS = -O0 -g -trace/" < makefile_mtemp > Makefile
   #sed "s/^F90FLAGS = .*/F90FLAGS = -O0 -g -init=snan,arrays -traceback/" < makefile_mtemp > Makefile
elif [ $1 == 2 ]
then
   module load intel mpich
   echo "use intel to compile with flag -O2"
   echo "***************************************************"
   sed "s/^F90FLAGS = .*/F90FLAGS = -O2/" < makefile_mtemp > Makefile
elif [ $1 == 3 ]
then
   module load intel mpich
   echo "use intel to check floating point exception"
   echo "***************************************************"
   # sed "s/^F90FLAGS = .*/F90FLAGS = -O0 -g -init=snan,arrays -traceback/" < makefile_mtemp > Makefile
   sed "s/^F90FLAGS = .*/F90FLAGS = -O2 -init=snan,arrays -fp-speculation=safe -traceback/" < makefile_mtemp > Makefile
elif [ $1 == 4 ]
then
   module load pgi mpich
   echo "use pgi to compile with flag -O0 -g -C "
   echo "***************************************************"
   sed "s/^F90FLAGS = .*/F90FLAGS = -O0 -g -C/" < makefile_mtemp > Makefile
elif [ $1 == 5 ]
then
   module load intel mpich itac
   echo "use intel trace analyzer with -O0"
   echo "***************************************************"
   sed "s/^F90FLAGS = .*/F90FLAGS = -O0 -g -trace/" < makefile_mtemp > Makefile
elif [ $1 == 6 ]
then
   module load intel mpich
   echo "use -O2 and other optimization flags"
   echo "***************************************************"
   sed "s/^F90FLAGS = .*/F90FLAGS = -O2 -ipo -axCORE-AVX512,CORE-AVX2,AVX/" < makefile_mtemp > Makefile
else
   echo "wrong input argument"
   exit 1
fi
make clean
make
