#!/bin/bash

if [ $# == 0 ]
then
   echo "need to have input argument"
   exit 1
fi

if [ $# -ne 3 ]
then
   rm -f ./output/*
fi

if [ $# == 1 ]
then
   mpirun -np $1 ./gems.exe
elif [ $# -ge 2 ] && [ $2 == c ]
then
   mpirun -np $1 ./gems.exe | tee copyscreen.txt
else
   mpirun -np $1 ./gems.exe
fi

concatenate_output.sh

